"""rename department

Revision ID: ac8cb13fb212
Revises: acc387752edb
Create Date: 2023-11-14 22:32:05.632685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8cb13fb212'
down_revision = 'acc387752edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    op.drop_table('departments')
    # ### end Alembic commands ###
